language: python

# command to install dependencies
install:
  - make init

# command to run tests
script:
  - make flake8
  - make ci

cache: pip

jobs:
  include:
    - stage: test
      python: '3.7'
    - stage: test
      python: '3.8'